=begin
#Swagger API2Cart

#API2Cart

OpenAPI spec version: 1.0.0
Contact: contact@api2cart.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require "uri"

module SwaggerClient
  class BasketApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # Add item to basket
    # @param customer_id Retrieves orders specified by customer id
    # @param product_id Defines id of the product which should be added to the basket
    # @param [Hash] opts the optional parameters
    # @option opts [String] :variant_id Defines product&#39;s variants specified by variant id
    # @option opts [Float] :quantity Defines new items quantity (default to 0)
    # @option opts [String] :store_id Store Id
    # @return [InlineResponse20083]
    def basket_item_add(customer_id, product_id, opts = {})
      data, _status_code, _headers = basket_item_add_with_http_info(customer_id, product_id, opts)
      return data
    end

    # 
    # Add item to basket
    # @param customer_id Retrieves orders specified by customer id
    # @param product_id Defines id of the product which should be added to the basket
    # @param [Hash] opts the optional parameters
    # @option opts [String] :variant_id Defines product&#39;s variants specified by variant id
    # @option opts [Float] :quantity Defines new items quantity
    # @option opts [String] :store_id Store Id
    # @return [Array<(InlineResponse20083, Fixnum, Hash)>] InlineResponse20083 data, response status code and response headers
    def basket_item_add_with_http_info(customer_id, product_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: BasketApi.basket_item_add ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling BasketApi.basket_item_add"
      end
      # verify the required parameter 'product_id' is set
      if @api_client.config.client_side_validation && product_id.nil?
        fail ArgumentError, "Missing the required parameter 'product_id' when calling BasketApi.basket_item_add"
      end
      # resource path
      local_var_path = "/basket.item.add.json"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'product_id'] = product_id
      query_params[:'variant_id'] = opts[:'variant_id'] if !opts[:'variant_id'].nil?
      query_params[:'quantity'] = opts[:'quantity'] if !opts[:'quantity'].nil?
      query_params[:'store_id'] = opts[:'store_id'] if !opts[:'store_id'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/x-www-form-urlencoded'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['api_key', 'store_key']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse20083')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BasketApi#basket_item_add\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
