=begin
#Swagger API2Cart

#API2Cart

OpenAPI spec version: 1.0.0
Contact: contact@api2cart.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::BasketApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BasketApi' do
  before do
    # run before each test
    @instance = SwaggerClient::BasketApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BasketApi' do
    it 'should create an instance of BasketApi' do
      expect(@instance).to be_instance_of(SwaggerClient::BasketApi)
    end
  end

  # unit tests for basket_item_add
  # 
  # Add item to basket
  # @param customer_id Retrieves orders specified by customer id
  # @param product_id Defines id of the product which should be added to the basket
  # @param [Hash] opts the optional parameters
  # @option opts [String] :variant_id Defines product&#39;s variants specified by variant id
  # @option opts [Float] :quantity Defines new items quantity
  # @option opts [String] :store_id Store Id
  # @return [InlineResponse20083]
  describe 'basket_item_add test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
